name: Publish Package to npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - run: corepack enable
      # This should match the version set in package.json
      - run: yarn set version 3.3.0
      - run: yarn
      - run: 'echo "npmAuthToken: ${NPM_PUBLISH_TOKEN}" >> .yarnrc.yml'
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - run: yarn npm publish

